In [40]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [41]:
import requests

header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

r = requests.get("https://www.athletic.net/CrossCountry/Division/List.aspx?DivID=65066", headers=header)

dfs = pd.read_html(r.text)

In [42]:
df = pd.DataFrame(dfs[0])

In [43]:
df.head()

,0,1,2,3,4,5,6,7,8
0,NaN,NaN,NaN,Athlete,Time,ST,Team,Date,Meet
1,NaN,1.0,11.0,Evan Stevens,15:38.4PR,MO,Webb City,Sep 17,Missouri Southern Stampede
2,NaN,2.0,12.0,Josh Allison,15:50.6,MO,Hillsboro,Sep 2,First Capitol XC Meet
3,NaN,3.0,10.0,Liam Adair,15:50.9PR,MO,Smithville,Sep 17,Missouri Southern Stampede
4,NaN,4.0,11.0,Isaac Rivera,15:56.4PR,MO,Lincoln College Prep,Sep 1,Greg Wilson Classic

In [44]:
df.drop(index =0, inplace=True)

In [45]:
df.drop(columns=[0], inplace=True)

In [46]:
df[1].isnull()

1      False
2      False
3      False
4      False
5       True
       ...
96     False
97      True
98     False
99     False
100    False
Name: 1, Length: 100, dtype: bool

In [47]:
df.iloc[98]

1                     99.0
2                     11.0
3             James Warner
4                  18:22.4
5                       MO
6              St. Charles
7                    Sep 2
8    First Capitol XC Meet
Name: 99, dtype: object

In [48]:
df[1].isnull().sum()

6

In [49]:
df[1].isnull().sum()

6

In [50]:
nulls = df[df[1].isnull()]

In [51]:
nulls

,1,2,3,4,5,6,7,8
5,NaN,12.0,James Wortham,15:56.4PR,MO,St. Charles West,Sep 10,Linn Cross Country Invitational
11,NaN,12.0,Ryan Seabaugh,16:26.3PR,MO,Central (Cape Girardeau),Sep 17,Cape Central XC Invitational
49,NaN,9.0,Carson Driemeier,17:37.9PR,MO,Festus,Sep 17,Festus Bowles Invitational
69,NaN,10.0,David Munger,18:00.4PR,MO,Hannibal,Sep 2,Mexico Invite
74,NaN,10.0,Victor Salas,18:04.3PR,MO,Monett,Sep 20,Riann Lubinski Invitational
97,NaN,10.0,Thomas Pratz,18:20.5PR,MO,Rolla,Sep 10,Lebanon Invitational

In [52]:
df

,1,2,3,4,5,6,7,8
1,1.0,11.0,Evan Stevens,15:38.4PR,MO,Webb City,Sep 17,Missouri Southern Stampede
2,2.0,12.0,Josh Allison,15:50.6,MO,Hillsboro,Sep 2,First Capitol XC Meet
3,3.0,10.0,Liam Adair,15:50.9PR,MO,Smithville,Sep 17,Missouri Southern Stampede
4,4.0,11.0,Isaac Rivera,15:56.4PR,MO,Lincoln College Prep,Sep 1,Greg Wilson Classic
5,NaN,12.0,James Wortham,15:56.4PR,MO,St. Charles West,Sep 10,Linn Cross Country Invitational
...,...,...,...,...,...,...,...,...
96,96.0,10.0,Tanner Jenks,18:20.5PR,MO,Platte County,Sep 3,Tim Nixon Invitational
97,NaN,10.0,Thomas Pratz,18:20.5PR,MO,Rolla,Sep 10,Lebanon Invitational
98,98.0,11.0,Joshua Schnurbusch,18:21.3PR,MO,Notre Dame (Cape Girardeau),Sep 17,Cape Central XC Invitational
99,99.0,11.0,James Warner,18:22.4,MO,St. Charles,Sep 2,First Capitol XC Meet
100,100.0,12.0,Colin Miller,18:23.9PR,MO,Smithville,Sep 17,Missouri Southern Stampede

In [53]:
df[1][5] = 5.0

C:\Users\Nolan\AppData\Local\Temp/ipykernel_23332/1679497386.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[1][5] = 5.0

In [54]:
df

,1,2,3,4,5,6,7,8
1,1.0,11.0,Evan Stevens,15:38.4PR,MO,Webb City,Sep 17,Missouri Southern Stampede
2,2.0,12.0,Josh Allison,15:50.6,MO,Hillsboro,Sep 2,First Capitol XC Meet
3,3.0,10.0,Liam Adair,15:50.9PR,MO,Smithville,Sep 17,Missouri Southern Stampede
4,4.0,11.0,Isaac Rivera,15:56.4PR,MO,Lincoln College Prep,Sep 1,Greg Wilson Classic
5,5.0,12.0,James Wortham,15:56.4PR,MO,St. Charles West,Sep 10,Linn Cross Country Invitational
...,...,...,...,...,...,...,...,...
96,96.0,10.0,Tanner Jenks,18:20.5PR,MO,Platte County,Sep 3,Tim Nixon Invitational
97,NaN,10.0,Thomas Pratz,18:20.5PR,MO,Rolla,Sep 10,Lebanon Invitational
98,98.0,11.0,Joshua Schnurbusch,18:21.3PR,MO,Notre Dame (Cape Girardeau),Sep 17,Cape Central XC Invitational
99,99.0,11.0,James Warner,18:22.4,MO,St. Charles,Sep 2,First Capitol XC Meet
100,100.0,12.0,Colin Miller,18:23.9PR,MO,Smithville,Sep 17,Missouri Southern Stampede

In [55]:
df[1][97] = 97.0

C:\Users\Nolan\AppData\Local\Temp/ipykernel_23332/3814775000.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[1][97] = 97.0

In [56]:
nulls

,1,2,3,4,5,6,7,8
5,NaN,12.0,James Wortham,15:56.4PR,MO,St. Charles West,Sep 10,Linn Cross Country Invitational
11,NaN,12.0,Ryan Seabaugh,16:26.3PR,MO,Central (Cape Girardeau),Sep 17,Cape Central XC Invitational
49,NaN,9.0,Carson Driemeier,17:37.9PR,MO,Festus,Sep 17,Festus Bowles Invitational
69,NaN,10.0,David Munger,18:00.4PR,MO,Hannibal,Sep 2,Mexico Invite
74,NaN,10.0,Victor Salas,18:04.3PR,MO,Monett,Sep 20,Riann Lubinski Invitational
97,NaN,10.0,Thomas Pratz,18:20.5PR,MO,Rolla,Sep 10,Lebanon Invitational

In [58]:
df[1][49] = 49.0
df[1][69] = 69.0
df[1][74] = 74.0

C:\Users\Nolan\AppData\Local\Temp/ipykernel_23332/2201805841.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[1][49] = 49.0
C:\Users\Nolan\AppData\Local\Temp/ipykernel_23332/2201805841.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[1][69] = 69.0
C:\Users\Nolan\AppData\Local\Temp/ipykernel_23332/2201805841.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[1][74] = 74.0

In [61]:
df[1].isnull().sum()

1

In [62]:
df[df[1].isnull()]

,1,2,3,4,5,6,7,8
11,NaN,12.0,Ryan Seabaugh,16:26.3PR,MO,Central (Cape Girardeau),Sep 17,Cape Central XC Invitational

In [63]:
df[1][11] = 11.0

C:\Users\Nolan\AppData\Local\Temp/ipykernel_23332/2472594354.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[1][11] = 11.0

In [64]:
df.isnull().sum()

1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64